WebSite/Entities/Models/Afiliado.cs
using System.ComponentModel.DataAnnotations;

namespace WebSite.Entities.Models
{
    public class Afiliado: IdentityBase
    {
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Cuit { get; set; }

        public string NombreCompleto => Nombre + " " + Apellido;
    }
}

WebSite/Entities/Models/IdentityBase.cs
using System.ComponentModel.DataAnnotations;

namespace WebSite.Entities.Models
{
    public class IdentityBase
    {
        [Key]
        public int Id { get; set; }
    }
}

WebSite/Controllers/AfiliadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSite.Business;
using WebSite.Entities.Models;

namespace WebSite.Controllers
{
    public class AfiliadoController : Controller
    {
        // GET: Afiliado
        public ActionResult Index()
        {
            var biz = new AfiliadoBiz();
            var model = biz.Listar();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Afiliado model)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                var biz = new AfiliadoBiz();
                biz.Agregar(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var biz = new AfiliadoBiz();
            var model = biz.TraerAfiliado(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Afiliado model)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                var biz = new AfiliadoBiz();
                biz.Actualizar(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(model);
            }
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var biz = new AfiliadoBiz();
            var model = biz.TraerAfiliado(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(Afiliado model)
        {
            var biz = new AfiliadoBiz();
            biz.Eliminar(model);
            return RedirectToAction("Index");
        }
    }
}

WebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebSite/Views/Afiliado/Create.cshtml
@model WebSite.Entities.Models.Afiliado

@{
    ViewBag.Title = "Nuevo Afiliado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo Afiliado</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Afiliado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 btnAccion">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="regresar">
    @Html.ActionLink("Regresar", "Index")
</div>

WebSite/Views/Afiliado/Delete.cshtml
@model WebSite.Entities.Models.Afiliado

@{
    ViewBag.Title = "Eliminar Afiliado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Afiliado</h2>

<h3>Esta seguro de eliminar al Afiliado?</h3>
<div>
    <h4>Afiliado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cuit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cuit)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color regresar">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

WebSite/Views/Afiliado/Index.cshtml
@model IEnumerable<WebSite.Entities.Models.Afiliado>

@{
    ViewBag.Title = "Obra Social";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Afiliados</h2>

<p>
    @Html.ActionLink("Nuevo Afiliado", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cuit)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NombreCompleto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cuit)
        </td>
        <td>
            @Html.ActionLink("Editar", "Update", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebSite/Views/Afiliado/Update.cshtml
@model WebSite.Entities.Models.Afiliado

@{
    ViewBag.Title = "Actualizar Afiliado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Actualizar Afiliado</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Afiliado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cuit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cuit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cuit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group btnAccion">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="regresar">
    @Html.ActionLink("Regresar", "Index")
</div>

WebSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Obra Social";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bienvenido</h2>

<div id="logo">
    <h1></h1>
</div>

WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div id="contenedor">
        <header>
            <div id="logo">
                <h1></h1>
            </div>
            <div id="buscador">
                <form action="#" method="post">
                    Buscar &nbsp;
                    <input name="busqueda" type="text" />
                </form>
            </div>
            <div class="clear">
            </div>
        </header>
        <nav>
            <ul id="menu_principal">
                <li> <a href="/">Home</a> </li>
                <li>
                    <a href="@Url.Action("Index", "Afiliado")">Afiliados</a>
                </li>
            </ul>
        </nav>
        <section>
            @RenderBody()
        </section>
        <aside>
            <p>Opciones</p>
        </aside>
        <footer>
            <p> Datos de la WebSite - 2021</p>
        </footer>
    </div>
</body>
</html>